export const GET_VALUES = 'GET_VALUES'
export const TOGGLE = 'TOGGLE'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const GET_USER = 'GET_USER'
export const UPDATE_AUTH = 'UPDATE_AUTH'
export const SET_FAVORITE = 'SET_FAVORITE'
export const SET_TOWATCH = 'SET_TOWATCH'
